ambs/dashboard/routes.py
from flask import render_template, Blueprint
from ambs.models.nda_models import NdaDataModel

main = Blueprint('main', __name__)

nda_inst = NdaDataModel()
@main.route("/") 
# @main.route("/dashboard")
def dashboard():
    nda_chart_data = nda_inst.get_district()
    count = []
    district = []

    for item in nda_chart_data:
        count.append(item['count'])
        district.append(item['district'])

    # dist = nda_chart_data.drugshop
    # print (dist)
    # return jsonify(district)

    return render_template('dashboard/index.html', district=district, count=count, nda_chart_data=nda_chart_data)


# return render_template('dashboard/index.html', title='Dashboard')

ambs/dashboard_ura/routes.py
from flask import render_template, Blueprint
from ambs.models.models import AmbsModel
from flask import jsonify
ura_dashboard = Blueprint('ura_dashboard', __name__)

nda_inst = AmbsModel()


@ura_dashboard.route("/ura_data")
def dashboard():
    ura_chart_data = nda_inst.get_co_name()
    count = []
    co_name = []

    for item in ura_chart_data:
        count.append(item['count'])
        co_name.append(item['co_name'])

    # dist = nda_chart_data.drugshop
    # print (dist)
    # return jsonify(ura_chart_data)

    return render_template('dashboard/ura_index.html', co_name=co_name, count=count, ura_chart_data=ura_chart_data)

ambs/importers/routes.py
from flask import render_template, jsonify, Blueprint
from ambs.models.models import AmbsModel

model_inst = AmbsModel()

importer = Blueprint('importers', __name__)


@importer.route('/imported_drugs')
def imported_drugs():
    # med_id = 1
    meds = model_inst.get_all_med()

    # meds=model_inst.single_med(med_id)
    # return jsonify({"all medicines": meds})

    return render_template('importers/index.html', title='importers', len = len(meds), meds=meds)

@importer.route('/data')
def data():
    # med_id = 1
    data1 = model_inst.get_chart_data()

      # return jsonify({"all medicines": data})

    return render_template('importers/index.html', title='importers', len = len(data1), data1=data1)


@importer.route('/imported_drugs/<int:med_id>')
def imported_drug_by_id(med_id):
    single_med = model_inst.single_med(med_id)
    return render_template('importers/single_data_field.html', title='importers', single_med=single_med)
    # return jsonify({"medicines per year": single_med})


@importer.route('/imported_by_year')
def imported_drug_by_year():

    meds_per_year = model_inst.query_by_year()
    return jsonify({"medicines per year": meds_per_year})
    # return render_template('importers/single_data_field.html', title='importers', meds_per_year=meds_per_year)


@importer.route('/imported_by_year')
def imported_by_year():
    meds_year = model_inst.query_year()
    return jsonify({"medicines per year": meds_year})
    # return render_template('importers/single_data_field.html', title='importers', meds_year=meds_year)

ambs/nda/routes.py
from flask import render_template, jsonify, Blueprint
from ambs.models.models import AmbsModel
from ambs.models.nda_models import NdaDataModel

model_inst = AmbsModel()
nda_inst = NdaDataModel()

nda = Blueprint('nda', __name__)


@nda.route('/nda_data')
def nda_get_data():
    # med_id = 1
    data = nda_inst.get_nda_data()

    # return jsonify({"all nda": data})

    return render_template('nda/index.html', title='nda', len=len(data), data=data)


@nda.route('/nda_district')
def nda_get_district_drugshop():
    # med_id = 1
    nda_chart_data = nda_inst.get_district()
    count = []
    district = []

    for item in nda_chart_data:
        count.append(item['count'])
        district.append(item['district'])

    # dist = nda_chart_data.drugshop
    # print (dist)
    # return jsonify(district)

    return render_template('dashboard/index.html', district=district, count=count, nda_chart_data=nda_chart_data)


# @nda.route('/nda_rugshop')
# def nda_get_drugshop():
#     # med_id = 1
#     drugshop = nda_inst.get_drugshop()
#
#     return jsonify({"drug shop": drugshop})

    # return render_template('dashboard/index.html', title='nda', len = len(drugshop), drugshop=drugshop)

ambs/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>AMBS | Home</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{ url_for('static',filename='plugins/fontawesome-free/css/all.min.css') }}  ">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{ url_for('static',filename='plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static',filename='plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">



  <script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
  <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
  
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static',filename='dist/css/adminlte.min.css') }}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
<!--  <script-->
<!--  src="https://code.jquery.com/jquery-3.3.1.js"-->
<!--  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="-->
<!--  crossorigin="anonymous"></script>-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#"><i
            class="fas fa-th-large"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="" class="brand-link">
      <img src="{{ url_for('static',filename='dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">ANMS SYS</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ url_for('static',filename='dist/img/user2-160x160.jpg') }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Mildred Nakayuki</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ url_for('main.dashboard')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>NDA Dashboard</p>
                </a>

                <a href="{{ url_for('ura_dashboard.dashboard')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>URA Dashboard</p>
                </a>
              </li>
               <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Data Representation
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

              <li class="nav-item">
                <a href="{{ url_for('importers.imported_drugs')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Imported Drugs</p>
                </a>
              </li>

               <li class="nav-item">
                <a href="{{ url_for('nda.nda_get_data')}}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>NDA DATA</p>
                </a>
              </li>
            </ul>
          </li>

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      
        {% block content %} {% endblock content%}

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2019 <a href="">Dynamic Project Managers</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.1
    </div>
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<script src="{{ url_for('static',filename='plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap -->
<script src="{{ url_for('static',filename='plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- overlayScrollbars -->
<script src="{{ url_for('static',filename='plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static',filename='dist/js/adminlte.js') }}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{{ url_for('static',filename='dist/js/demo.js') }}"></script>

<!-- PAGE PLUGINS -->
<!-- jQuery Mapael -->
<script src="{{ url_for('static',filename='plugins/jquery-mousewheel/jquery.mousewheel.js') }}"></script>
<script src="{{ url_for('static',filename='plugins/raphael/raphael.min.js') }}"></script>
<script src="{{ url_for('static',filename='plugins/jquery-mapael/jquery.mapael.min.js') }}"></script>
<script src="{{ url_for('static',filename='plugins/jquery-mapael/maps/usa_states.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ url_for('static',filename='plugins/chart.js/Chart.min.js') }}"></script>
<!-- DataTables -->
<script src="{{ url_for('static',filename='plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ url_for('static',filename='plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
<!-- PAGE SCRIPTS -->
<!--<script src="{{ url_for('static',filename='dist/js/pages/dashboard2.js') }}"></script>-->
<script>
  $(function () {
    $('#example2').DataTable();
  });
</script>
</body>
</html>